#!/bin/bash
# Quick Git Authentication Fix Script
# This will help you set up Git authentication with GitHub

echo "================================"
echo "Git Authentication Fix Assistant"
echo "================================"
echo ""

# Step 1: Set up credential helper
echo "✓ Step 1: Configuring Git credential helper..."
git config --global credential.helper osxkeychain
echo "  Credential helper configured to use macOS Keychain"
echo ""

# Step 2: Check current configuration
echo "Step 2: Current Git Configuration:"
echo "-----------------------------------"
echo "Remote URL:"
git config --get remote.origin.url || echo "  No remote configured"
echo ""
echo "User Name:"
git config --get user.name || echo "  Not configured"
echo ""
echo "User Email:"
git config --get user.email || echo "  Not configured"
echo ""

# Step 3: Instructions
echo "================================"
echo "NEXT STEPS:"
echo "================================"
echo ""
echo "1. CREATE A GITHUB PERSONAL ACCESS TOKEN:"
echo "   → Go to: https://github.com/settings/tokens"
echo "   → Click 'Generate new token' → 'Generate new token (classic)'"
echo "   → Name: 'Archiving Project Token'"
echo "   → Select scope: ✓ repo (full control)"
echo "   → Click 'Generate token'"
echo "   → COPY THE TOKEN (starts with ghp_...)"
echo ""
echo "2. PUSH YOUR CODE:"
echo "   Run: git push -u origin main"
echo ""
echo "3. WHEN PROMPTED, ENTER:"
echo "   Username: d-mcguinness"
echo "   Password: [PASTE YOUR TOKEN HERE]"
echo ""
echo "   ⚠️  Use the TOKEN as password, NOT your GitHub password!"
echo ""
echo "4. The token will be saved in your macOS Keychain"
echo "   Future pushes won't need credentials"
echo ""
echo "================================"
echo "ALTERNATIVE: Use SSH Instead"
echo "================================"
echo ""
echo "If you prefer SSH authentication:"
echo "   1. Generate SSH key:"
echo "      ssh-keygen -t ed25519 -C 'your-email@example.com'"
echo ""
echo "   2. Copy public key:"
echo "      pbcopy < ~/.ssh/id_ed25519.pub"
echo ""
echo "   3. Add to GitHub:"
echo "      https://github.com/settings/keys"
echo ""
echo "   4. Change remote to SSH:"
echo "      git remote set-url origin git@github.com:d-mcguinness/archiving.git"
echo ""
echo "================================"
