#!/bin/bash
# GitHub Personal Access Token Setup Guide
# Run this script to get step-by-step instructions

clear
echo "════════════════════════════════════════════════════════════════"
echo "   GITHUB PERSONAL ACCESS TOKEN SETUP - STEP BY STEP"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Git is now configured to save your token securely"
echo "✅ Your remote is set to: https://github.com/d-mcguinness/archiving.git"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "   STEP 1: CREATE GITHUB TOKEN (Do this in your browser)"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1. Open this URL in your browser:"
echo "   👉 https://github.com/settings/tokens/new"
echo ""
echo "2. Fill in the form:"
echo "   ┌─────────────────────────────────────────────────────┐"
echo "   │ Note: Archiving Project Token                       │"
echo "   │                                                      │"
echo "   │ Expiration: 90 days (or choose your preference)     │"
echo "   │                                                      │"
echo "   │ Select scopes:                                       │"
echo "   │   ☑ repo (Full control of private repositories)    │"
echo "   │                                                      │"
echo "   └─────────────────────────────────────────────────────┘"
echo ""
echo "3. Scroll down and click the green 'Generate token' button"
echo ""
echo "4. COPY THE TOKEN (it looks like this):"
echo "   ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
echo ""
echo "   ⚠️  IMPORTANT: You can only see this token ONCE!"
echo "   ⚠️  Copy it to your clipboard NOW!"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "   STEP 2: USE THE TOKEN (After copying it)"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Run this command to push your code:"
echo ""
echo "   git push -u origin main"
echo ""
echo "When prompted, enter:"
echo ""
echo "   Username for 'https://github.com': d-mcguinness"
echo "   Password for 'https://d-mcguinness@github.com': <PASTE_TOKEN_HERE>"
echo ""
echo "   📝 Use CMD+V to paste the token"
echo "   📝 The token is your PASSWORD (not your GitHub password!)"
echo "   📝 You won't see the token as you paste it (this is normal)"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "   STEP 3: VERIFY IT WORKED"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "After entering your token, you should see:"
echo ""
echo "   Enumerating objects: 100, done."
echo "   Counting objects: 100% (100/100), done."
echo "   Writing objects: 100% (100/100), done."
echo "   To https://github.com/d-mcguinness/archiving.git"
echo "    * [new branch]      main -> main"
echo ""
echo "✅ Your token will be saved in macOS Keychain"
echo "✅ Future pushes won't ask for credentials"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "   TROUBLESHOOTING"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "❌ If you get 'Repository not found':"
echo "   → Create the repo first at https://github.com/new"
echo "   → Name it 'archiving'"
echo "   → DON'T check 'Initialize with README'"
echo ""
echo "❌ If token doesn't work:"
echo "   → Make sure you checked the 'repo' scope"
echo "   → Make sure you copied the FULL token (starts with ghp_)"
echo "   → Token is the PASSWORD, not the username"
echo ""
echo "❌ To clear old credentials and try again:"
echo "   git credential-osxkeychain erase <<EOF"
echo "   protocol=https"
echo "   host=github.com"
echo ""
echo "   EOF"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Ready to start?"
echo ""
echo "1️⃣  Open: https://github.com/settings/tokens/new"
echo "2️⃣  Create token with 'repo' scope"
echo "3️⃣  Copy the token"
echo "4️⃣  Run: git push -u origin main"
echo "5️⃣  Paste token when prompted"
echo ""
echo "════════════════════════════════════════════════════════════════"
