-- V1 baseline: the complete schema, generated from the JPA entities via
-- Hibernate (PostgreSQL dialect). On Postgres profiles Flyway applies this and
-- Hibernate runs with ddl-auto=validate against it. Evolve the schema only via
-- new V_n migrations (never edit this file). H2 unit tests bypass Flyway and use
-- ddl-auto=create-drop. NOTE: the reuse_reported column from PR #23 is
-- intentionally NOT here (not on this branch) — it lands as V2 when #23 rebases.


    create table aip_users (
        aip_id bigint not null,
        user_id bigint not null,
        primary key (aip_id, user_id)
    );

    create table aips (
        billable boolean default true not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        owner_id bigint not null,
        root_element_id bigint unique,
        source_sip_id bigint,
        tenant_id bigint not null,
        updated_at timestamp(6),
        description varchar(1000),
        content TEXT,
        standard varchar(255) not null check (standard in ('NOARK5','OAIS','PREMIS','DUBLIN_CORE','METS','EAD','BAGIT','ISADG','MODS','EARK')),
        status varchar(255) not null check (status in ('DRAFT','BUILDING','VALIDATED','STORED','REJECTED')),
        title varchar(255) not null,
        primary key (id)
    );

    create table archive_users (
        archive_id bigint not null,
        user_id bigint not null,
        primary key (archive_id, user_id)
    );

    create table archives (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        owner_id bigint not null,
        root_element_id bigint unique,
        tenant_id bigint not null,
        updated_at timestamp(6),
        description varchar(1000),
        content TEXT,
        standard varchar(255) not null check (standard in ('NOARK5','OAIS','PREMIS','DUBLIN_CORE','METS','EAD','BAGIT','ISADG','MODS','EARK')),
        status varchar(255) not null check (status in ('DRAFT','PUBLISHED','ARCHIVED','DELETED')),
        title varchar(255) not null,
        primary key (id)
    );

    create table dip_users (
        dip_id bigint not null,
        user_id bigint not null,
        primary key (dip_id, user_id)
    );

    create table dips (
        billable boolean default true not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        owner_id bigint not null,
        root_element_id bigint unique,
        source_aip_id bigint,
        tenant_id bigint not null,
        updated_at timestamp(6),
        description varchar(1000),
        content TEXT,
        standard varchar(255) not null check (standard in ('NOARK5','OAIS','PREMIS','DUBLIN_CORE','METS','EAD','BAGIT','ISADG','MODS','EARK')),
        status varchar(255) not null check (status in ('DRAFT','PREPARED','DISSEMINATED','EXPIRED','REJECTED')),
        title varchar(255) not null,
        primary key (id)
    );

    create table documents (
        billable boolean default true not null,
        archive_id bigint,
        created_at timestamp(6) not null,
        file_size bigint,
        id bigint generated by default as identity,
        sip_id bigint,
        tenant_id bigint,
        updated_at timestamp(6),
        uploaded_at timestamp(6),
        user_id bigint not null,
        content_type varchar(100),
        file_name varchar(500) not null,
        file_key varchar(1000) not null,
        file_url varchar(2000),
        description TEXT,
        status varchar(255) not null check (status in ('ACTIVE','ARCHIVED','DELETED','PENDING_REVIEW','APPROVED','REJECTED')),
        title varchar(255) not null,
        primary key (id)
    );

    create table element_links (
        directional boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        source_element_id bigint not null,
        target_element_id bigint not null,
        link_type varchar(50) not null,
        created_by varchar(255),
        description TEXT,
        label varchar(255),
        metadata TEXT,
        primary key (id)
    );

    create table elements (
        is_root boolean,
        sort_order integer,
        archive_id bigint,
        closed_at timestamp(6),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        parent_element_id bigint,
        updated_at timestamp(6),
        status varchar(50) not null,
        entity_name varchar(100) not null,
        entity_type varchar(100) not null,
        title varchar(500) not null,
        closed_by varchar(255),
        created_by varchar(255),
        description TEXT,
        element_identifier varchar(255) not null,
        english_name varchar(255),
        metadata TEXT,
        norwegian_name varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

    create table fields (
        element_id bigint not null,
        id bigint generated by default as identity,
        type varchar(50) not null,
        label varchar(255),
        name varchar(255) not null,
        value TEXT,
        primary key (id)
    );

    create table package_users (
        package_id bigint not null,
        user_id bigint not null,
        primary key (package_id, user_id)
    );

    create table packages (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        owner_id bigint not null,
        root_element_id bigint unique,
        source_archive_id bigint,
        source_package_id bigint,
        tenant_id bigint not null,
        updated_at timestamp(6),
        stage varchar(10) not null check (stage in ('SIP','AIP','DIP')),
        status varchar(20) not null check (status in ('DRAFT','REJECTED','SUBMITTED','VALIDATED','ACCEPTED','BUILDING','STORED','PREPARED','DISSEMINATED','EXPIRED')),
        description varchar(1000),
        content TEXT,
        standard varchar(255) not null check (standard in ('NOARK5','OAIS','PREMIS','DUBLIN_CORE','METS','EAD','BAGIT','ISADG','MODS','EARK')),
        title varchar(255) not null,
        primary key (id)
    );

    create table premium_package_events (
        generated_at timestamp(6) not null,
        id bigint generated by default as identity,
        package_type varchar(8) not null check (package_type in ('AIP','DIP')),
        tenant_id bigint not null,
        standard varchar(32) not null,
        primary key (id)
    );

    create table refresh_tokens (
        revoked boolean not null,
        created_at timestamp(6) not null,
        expires_at bigint not null,
        id bigint generated by default as identity,
        rotated_to_id bigint,
        user_id bigint not null,
        token_hash varchar(64) not null unique,
        primary key (id)
    );

    create table sip_users (
        sip_id bigint not null,
        user_id bigint not null,
        primary key (sip_id, user_id)
    );

    create table sips (
        archive_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        owner_id bigint not null,
        root_element_id bigint unique,
        tenant_id bigint not null,
        updated_at timestamp(6),
        description varchar(1000),
        content TEXT,
        standard varchar(255) not null check (standard in ('NOARK5','OAIS','PREMIS','DUBLIN_CORE','METS','EAD','BAGIT','ISADG','MODS','EARK')),
        status varchar(255) not null check (status in ('DRAFT','SUBMITTED','VALIDATED','ACCEPTED','REJECTED')),
        title varchar(255) not null,
        primary key (id)
    );

    create table tenant_overage_budgets (
        overage_opt_in boolean not null,
        id bigint generated by default as identity,
        premium_package_overage_limit bigint not null,
        storage_overage_limit_bytes bigint not null,
        tenant_id bigint not null unique,
        primary key (id)
    );

    create table tenants (
        allow_external_sharing boolean,
        enable_audit_log boolean,
        max_archives integer,
        max_users integer,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        max_storage_bytes bigint,
        updated_at timestamp(6),
        default_language varchar(20),
        timezone varchar(50),
        custom_domain varchar(100),
        domain varchar(100) not null unique,
        name varchar(100) not null,
        description varchar(1000),
        display_name varchar(255),
        owner_id varchar(255) not null,
        plan varchar(255) not null check (plan in ('FREE','BASIC','PROFESSIONAL','ENTERPRISE','CUSTOM')),
        status varchar(255) not null check (status in ('ACTIVE','INACTIVE','SUSPENDED','PENDING_ACTIVATION','TRIAL','EXPIRED')),
        primary key (id)
    );

    create table usage_snapshots (
        period date not null,
        captured_at timestamp(6) not null,
        id bigint generated by default as identity,
        premium_packages_generated bigint not null,
        seat_count bigint not null,
        storage_bytes bigint not null,
        tenant_id bigint not null,
        primary key (id),
        unique (tenant_id, period)
    );

    create table user_tenant (
        created_at timestamp(6),
        id bigint generated by default as identity,
        tenant_id bigint not null,
        user_id bigint not null,
        primary key (id),
        unique (tenant_id, user_id)
    );

    create table users (
        age integer,
        id bigint generated by default as identity,
        role varchar(20),
        username varchar(50) unique,
        name varchar(100) not null,
        email varchar(255) not null unique,
        password_hash varchar(255),
        primary key (id)
    );

    create index idx_aip_tenant_id 
       on aips (tenant_id);

    create index idx_aip_owner_id 
       on aips (owner_id);

    create index idx_aip_status 
       on aips (status);

    create index idx_aip_standard 
       on aips (standard);

    create index idx_aip_created_at 
       on aips (created_at);

    create index idx_aip_updated_at 
       on aips (updated_at);

    create index idx_aip_tenant_status 
       on aips (tenant_id, status);

    create index idx_aip_owner_status 
       on aips (owner_id, status);

    create index idx_archive_tenant_id 
       on archives (tenant_id);

    create index idx_archive_owner_id 
       on archives (owner_id);

    create index idx_archive_status 
       on archives (status);

    create index idx_archive_standard 
       on archives (standard);

    create index idx_archive_created_at 
       on archives (created_at);

    create index idx_archive_updated_at 
       on archives (updated_at);

    create index idx_archive_tenant_status 
       on archives (tenant_id, status);

    create index idx_archive_owner_status 
       on archives (owner_id, status);

    create index idx_dip_tenant_id 
       on dips (tenant_id);

    create index idx_dip_owner_id 
       on dips (owner_id);

    create index idx_dip_status 
       on dips (status);

    create index idx_dip_standard 
       on dips (standard);

    create index idx_dip_created_at 
       on dips (created_at);

    create index idx_dip_updated_at 
       on dips (updated_at);

    create index idx_dip_tenant_status 
       on dips (tenant_id, status);

    create index idx_dip_owner_status 
       on dips (owner_id, status);

    create index idx_document_user_id 
       on documents (user_id);

    create index idx_document_tenant_id 
       on documents (tenant_id);

    create index idx_document_archive_id 
       on documents (archive_id);

    create index idx_document_sip_id 
       on documents (sip_id);

    create index idx_document_created_at 
       on documents (created_at);

    create index idx_document_status 
       on documents (status);

    create index idx_el_link_source 
       on element_links (source_element_id);

    create index idx_el_link_target 
       on element_links (target_element_id);

    create index idx_el_link_type 
       on element_links (link_type);

    create index idx_pkg_tenant_id 
       on packages (tenant_id);

    create index idx_pkg_owner_id 
       on packages (owner_id);

    create index idx_pkg_stage 
       on packages (stage);

    create index idx_pkg_status 
       on packages (status);

    create index idx_pkg_standard 
       on packages (standard);

    create index idx_pkg_created_at 
       on packages (created_at);

    create index idx_pkg_tenant_stage 
       on packages (tenant_id, stage);

    create index idx_pkg_owner_status 
       on packages (owner_id, status);

    create index idx_ppe_tenant 
       on premium_package_events (tenant_id);

    create index idx_ppe_tenant_generated 
       on premium_package_events (tenant_id, generated_at);

    create index idx_refresh_tokens_user_id 
       on refresh_tokens (user_id);

    create index idx_sip_tenant_id 
       on sips (tenant_id);

    create index idx_sip_owner_id 
       on sips (owner_id);

    create index idx_sip_status 
       on sips (status);

    create index idx_sip_standard 
       on sips (standard);

    create index idx_sip_created_at 
       on sips (created_at);

    create index idx_sip_updated_at 
       on sips (updated_at);

    create index idx_sip_tenant_status 
       on sips (tenant_id, status);

    create index idx_sip_owner_status 
       on sips (owner_id, status);

    create index idx_sip_archive_id 
       on sips (archive_id);

    alter table if exists aip_users 
       add constraint FKdvi2hm9e9kfxq6qiaqedsyjqk 
       foreign key (user_id) 
       references users;

    alter table if exists aip_users 
       add constraint FKjvs1l3gh94ouu4vldxela29dj 
       foreign key (aip_id) 
       references aips;

    alter table if exists aips 
       add constraint FK302w00l3qa5qm9ot5gpejydwq 
       foreign key (root_element_id) 
       references elements;

    alter table if exists archive_users 
       add constraint FKnaeq00ir99gehh1o6ci3x2ndx 
       foreign key (user_id) 
       references users;

    alter table if exists archive_users 
       add constraint FKe38odh6gaqmtrrbggmpx0fsw6 
       foreign key (archive_id) 
       references archives;

    alter table if exists archives 
       add constraint FKdn03lnk8bs86vx22k3wurma5y 
       foreign key (root_element_id) 
       references elements;

    alter table if exists dip_users 
       add constraint FK6lrq2efrgpvd0qo3shl32hn56 
       foreign key (user_id) 
       references users;

    alter table if exists dip_users 
       add constraint FK6ncv2tpmloa7mf0s3o732l39n 
       foreign key (dip_id) 
       references dips;

    alter table if exists dips 
       add constraint FKkd0gplcaa2n9fvscpwxi0g7u8 
       foreign key (root_element_id) 
       references elements;

    alter table if exists element_links 
       add constraint FKl5m2d6ivd2ciuyummjy8hdr2l 
       foreign key (source_element_id) 
       references elements;

    alter table if exists element_links 
       add constraint FK6n09okobyrh36o0abqy7l6qay 
       foreign key (target_element_id) 
       references elements;

    alter table if exists elements 
       add constraint FK5eq9un4r6x665jg3g82x47bby 
       foreign key (archive_id) 
       references archives;

    alter table if exists elements 
       add constraint FK9vaqqu2wp2rvshp114dwwo6pa 
       foreign key (parent_element_id) 
       references elements;

    alter table if exists fields 
       add constraint FKi4dpp3x7iqlqjrv6s6trmloe1 
       foreign key (element_id) 
       references elements;

    alter table if exists package_users 
       add constraint FKa0m3tkkxpp3xuvpx5i0ve7b5h 
       foreign key (user_id) 
       references users;

    alter table if exists package_users 
       add constraint FK2eleolrryj2938wji7j4ja8tm 
       foreign key (package_id) 
       references packages;

    alter table if exists packages 
       add constraint FK87btexcq5ekiesgi7ql0vjyow 
       foreign key (root_element_id) 
       references elements;

    alter table if exists sip_users 
       add constraint FKchmljfb4j4s65i4k7c5q6tvsl 
       foreign key (user_id) 
       references users;

    alter table if exists sip_users 
       add constraint FK8omvjftu10ykbgwm4nc8roj5k 
       foreign key (sip_id) 
       references sips;

    alter table if exists sips 
       add constraint FKmmcwquihqoeipjbsl476hua45 
       foreign key (root_element_id) 
       references elements;
