-- V3: outbox of billable meter quantities awaiting push to Stripe Billing Meters.
-- One row per (tenant, billing period, meter). quantity is integer: milli-GB-months
-- for storage_gb_month, package count for premium_packages. idempotency_key is
-- unique so recomputing a period upserts rather than duplicating.

CREATE TABLE stripe_meter_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant_id BIGINT NOT NULL,
    meter_name VARCHAR(64) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    quantity BIGINT NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL,
    attempts INTEGER NOT NULL,
    stripe_event_id VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    sent_at TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX uq_meter_report_idem ON stripe_meter_reports (idempotency_key);
CREATE INDEX idx_meter_report_status ON stripe_meter_reports (status);
